### ISSUE TITLE
Notify's not adhearing to positioning

### ISSUE THREAD

**Issue by Tomshiii** [XMCQCX/NotifyClass-NotifyCreator#3]
Hey hey!
I haven't had much in the way of time to look into what could be causing this issue (super busy with work lately, I'm so sorry) but ever since the last round of changes to your class it seems like they can sometimes no longer adhear to the defined positioning. If I use them by themselves in a test script all seems to work as expected but having them fire in an actual script seems (in my case) to have them appear in the center of the screen instead of the defined `BR`.

[here is a screenshot of it appearing in the center of the screen](https://github.com/XMCQCX/Notify_Class/assets/53557479/d1d268ee-67b1-4fa4-9819-66f089071f71)

and this is the line that calls it; [[447]](https://github.com/Tomshiii/ahk/blob/dev/Timer%20Scripts/autosave.ahk#L447) 
```c++
Notify.Show(, 'A save attempt is being made. Inputs may be temporarily blocked', 'iconi',,, 'POS=BR TC=black MC=black BC=DCCC75 DUR=4 show=Fade@250 hide=Fade@250')
```

[this is a screenshot of another one working just 20 lines earlier as expected](https://github.com/XMCQCX/Notify_Class/assets/53557479/72fa5d6f-350a-4666-9a0e-3196ea4e8788)

and the line that calls it; [[419]](https://github.com/Tomshiii/ahk/blob/dev/Timer%20Scripts/autosave.ahk#L419) 
```c++
Notify.Show(, 'Premiere save not required, cancelling...', 'iconi',,, 'POS=BR TC=black MC=black BC=75AEDC DUR=2 show=Fade@250 hide=Fade@250')
```

It might not be much help to you but [this](https://github.com/Tomshiii/ahk/blob/dev/Timer%20Scripts/autosave.ahk) is my script I've been noticing it in but as it relies on a whole lot of other code it might not do much for you in tracking down what might be causing this.

I tried moving it up line by line to see where it broke and it seems that as soon as I put it under line [[439]](https://github.com/Tomshiii/ahk/blob/dev/Timer%20Scripts/autosave.ahk#L439) is when it breaks which seems a little strange because it's [not really doing anything](https://github.com/Tomshiii/ahk/blob/dev/Timer%20Scripts/autosave.ahk#L225) that I would expect to cause any issues (esp bc it happens even if the function immediately terminates and doesn't even hit the loop or anything.

Let me know if there's anything more I can do/provide to help you track down what could be causing this, I'm super appreciative of all the work that has gone into this project! And if this is purely my own doing and I'm missing something obvious please feel free to tell me, I'm a self taught script kiddie just doing his best hahaha

**Comment by XMCQCX** [comment]
Hi,

I've never encountered this issue. Like you said, it seems a little strange because I also see nothing that I would expect to cause this.

First, check the variables set by MonitorGetWorkArea to see if they are make sense; [[365]](https://github.com/XMCQCX/Notify_Class/blob/16d961f87c761366346034c42f0c73f6a265a7ea/Notify.ahk#L365)

After that, confirm it goes into the BR case of this switch-case statement; [[449]](https://github.com/XMCQCX/Notify_Class/blob/16d961f87c761366346034c42f0c73f6a265a7ea/Notify.ahk#L449)

Next, look at the gPos variable prior to the creation of the GUI and verify the values make sense; [[513]](https://github.com/XMCQCX/Notify_Class/blob/16d961f87c761366346034c42f0c73f6a265a7ea/Notify.ahk#L513) 

Is there anything in the code that could potentially interrupt the Notify.Show() method, such as OnMessage, Window Hooks, Shell Hooks, etc.?

Try uncommenting all the Critical on/off function calls at the beginning and end of these methods: _Show, gDestroy, DestroyAllAtPosition, DestroyAll. In my test version, I removed all of them because, from my limited understanding of thread execution, I thought they could interfere with other code.

You said it wasn't an issue with the earlier version? You could also try with version [1.3.0](https://github.com/XMCQCX/Notify_Class/blob/38d84de2eb4c354fbe14512c2eabf9dd1a358fdb/Notify.ahk) to see if the issue was introduced in 1.4.1.

**Comment by XMCQCX** [comment]
@Tomshiii
After going over your post again, I don't think the problem lies with MonitorGetWorkArea or the switch-case statement like I thought. It's more likely related to when it tries to identify the highest or lowest GUI to adjust the Y position. ; [[436]](https://github.com/XMCQCX/Notify_Class/blob/16d961f87c761366346034c42f0c73f6a265a7ea/Notify.ahk#L436)

**Comment by XMCQCX** [comment]
@Tomshiii
I've been able to replicate the issue. It's likely related to the DetectHiddenWindows settings. If turned on, it will detect the hidden window that was created to set the width and height of the clickArea text control and position it above, hence in the middle of the screen. Hidden window: [[407]](https://github.com/XMCQCX/Notify_Class/blob/16d961f87c761366346034c42f0c73f6a265a7ea/Notify.ahk#L407)

The DetectHiddenWindows settings need to be set to 0. Change this;[[433]](https://github.com/XMCQCX/Notify_Class/blob/16d961f87c761366346034c42f0c73f6a265a7ea/Notify.ahk#L433)
```
tmmPrev := A_TitleMatchMode
SetTitleMatchMode('RegEx')        
        
for id in WinGetList('i)^NotifyGUI_' m['mon'] '_' m['pos'] ' ahk_class AutoHotkeyGUI') {            
    WinGetPos(&guiX, &guiY, &guiW, &guiH, id)
    Switch m['pos'], 'off' {
        case 'br', 'bc', 'bl': minMaxPosY := Min(minMaxPosY, guiY)               
        case 'tr', 'tc', 'tl', 'ct': minMaxPosY := Max(minMaxPosY, guiY + guiH)
    }
}

SetTitleMatchMode(tmmPrev)
```
To
```
tmmPrev := A_TitleMatchMode
dhwPrev := A_DetectHiddenWindows
SetTitleMatchMode('RegEx')   
DetectHiddenWindows(0)
               
for id in WinGetList('i)^NotifyGUI_' m['mon'] '_' m['pos'] ' ahk_class AutoHotkeyGUI') {            
    WinGetPos(&guiX, &guiY, &guiW, &guiH, 'ahk_id ' id)
    Switch m['pos'], 'off' {
        case 'br', 'bc', 'bl': minMaxPosY := Min(minMaxPosY, guiY)               
        case 'tr', 'tc', 'tl', 'ct': minMaxPosY := Max(minMaxPosY, guiY + guiH)
    }
}

SetTitleMatchMode(tmmPrev)
DetectHiddenWindows(dhwPrev)
```

**Comment by Tomshiii** [comment]
@XMCQCX
Thank you for taking the time to look into this in a little more depth, I apologise for not being able to get back to you sooner (timezones are fun).
That does indeed look to fix the issue on my end! I appreciate you tracking that down!

**Comment by XMCQCX** [comment]
@Tomshiii Thank you for reporting the issue. I have updated it to version 1.4.2. It only includes this fix.
